GeekText_Team2/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from GeekText_Team2 import db, app, mail, google
from flask_mail import Message
from threading import Thread
from sqlalchemy.exc import IntegrityError
from werkzeug.security import generate_password_hash, check_password_hash
from GeekText_Team2.models import User, Address, Payment_Info
from GeekText_Team2.users.forms import RegistrationForm, LoginForm, UpdateUserForm, UpdateShippingForm, UpdateAddressForm, AddPaymentInfo, ForgotForm, ChangePassword
from GeekText_Team2.users.picture_handler import add_profile_pic
from GeekText_Team2.models import BlogPost
from itsdangerous import URLSafeTimedSerializer
from GeekText_Team2.blog_posts.forms import BlogPostForm
import datetime

users = Blueprint('users', __name__, template_folder='templates/')


@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('core.home'))


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    forgot_form = ForgotForm()
    if form.validate_on_submit():
        # Grab the user from our User Models table
        user = User.query.filter_by(email=form.email.data).first()
        # Check that the user was supplied and the password is right
        # The verify_password method comes from the User object
        if user is not None:
            if user.check_password(form.password.data) and user is not None:
                # log in the user
                login_user(user)
            # If a user was trying to visit a page that requires a login
            # flask saves that URL as 'next'.
                next = request.args.get('next')
            # if that next exists we go to it, otherwise we'll go to
            # the welcome page.
                if next == None or not next[0] == '/':
                    next = url_for('books.list')

                return redirect(next)
    return render_template('login.html', form=form, forgot_form=forgot_form)


@users.route('/forgot_password?', methods=['GET', 'POST'])
def forgot_password(form):
    if form.validate_on_submit():
        email = form.email.data
        user = User.query.filter_by(email=email.lower()).first()
        # if user:

    return render_template("forgot_password.html")


@users.route('/register', methods=['GET', 'POST'])
def register():

    form = RegistrationForm()

    if form.validate_on_submit():
        try:
            user = User(first_name=form.first_name.data,
                        last_name=form.last_name.data,
                        email=form.email.data,
                        username=form.username.data,
                        password=form.password.data)

            db.session.add(user)
            db.session.commit()
            print("HERE")
            send_confirmation_email(user.email)
            flash(
                'Thanks for registering! Please check your email to confirm your email address.', 'success')
            st8 = form.state.data.capitalize()
            u_address = Address(user_id=user.id,
                                address=form.address.data,
                                city=form.city.data,
                                state=st8,
                                postal_code=form.zip_code.data,
                                phone_num=form.phone_num.data)

            db.session.add(u_address)
            db.session.commit()
            flash('Thanks for registering! Now you can login!')
            return redirect(url_for('users.login'))
        except IntegrityError:
            db.session.rollback()
            flash('ERROR! Email ({}) already exists.'.format(
                form.email.data), 'error')
    return render_template('register.html', form=form)

########################## SHIPPING INFO METHODS ############################
@users.route('/shipping_info', methods=['GET', 'POST'])
@login_required
def shipping_info():
    form = UpdateShippingForm()
    addr = 0
    addresses = current_user.address
    if form.validate_on_submit():
        new_address = Address(user_id=current_user.id,
                              address=form.address.data,
                              city=form.city.data,
                              state=form.state.data,
                              postal_code=form.zip_code.data,
                              phone_num=form.phone_num.data)

        #user = User.query.filter_by(address=form.email.data).first()

        print(new_address.address)
        db.session.add(new_address)
        db.session.commit()
        addresses = current_user.address
        redirect(url_for('users.shipping_info', form=form, addresses=addresses))

    return render_template('shipping.html', form=form, addresses=addresses, addr=addr)


@users.route('/shipping_info/<int:address_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_address(address_id):
    address = Address.query.filter_by(id=address_id).first()

    if address.user_id != current_user.id:
        abort(403)

    form = UpdateAddressForm()

    if form.validate_on_submit():
        address.address = form.address.data
        address.city = form.city.data
        address.state = form.state.data
        address.postal_code = form.zip_code.data
        address.phone_num = form.phone_num.data

        db.session.commit()
        flash('Address updated')
        return redirect(url_for('users.shipping_info'))

    return render_template('edit_address.html', form=form, address=address)


@users.route('/shipping_info/<int:address_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_address(address_id):
    address = Address.query.filter_by(id=address_id).first()

    if address.user_id != current_user.id:
        abort(403)

    db.session.delete(address)
    db.session.commit()
    flash('Address deleted')
    return redirect(url_for('users.shipping_info'))
#########################################################################

###################### PAYMENT INFO METHODS ##################################
@users.route('/payment_info', methods=['GET', 'POST'])
@login_required
def payment_info():
    if current_user.payment_info is not None:
        cards = current_user.payment_info

        redirect(url_for('users.payment_info', cards=cards))

    return render_template('payment_info.html', cards=cards)


@users.route('/add_card', methods=['GET', 'POST'])
@login_required
def add_card():
    form = AddPaymentInfo()
    if form.validate_on_submit():
        # m_y = form.exp_date.data
        # date_time = datetime.datetime.strptime(m_y, '%m/%y').date()
        # date = date_time.strftime("%m/%Y")
        # print(m_y)
        # print(date)
        c_card = Payment_Info(credit_number=form.card_num.data,
                              user_id=current_user.id,
                              cardholder=form.name.data,
                              expiration_date=form.exp_date.data,
                              csv=form.csv.data,
                              ZIP=form.zip.data)

        ex_card = Payment_Info.query.filter_by(
            credit_number=form.card_num.data).first()
        if ex_card is not None and ex_card.credit_number == c_card.credit_number and ex_card.user_id == c_card.user_id:
            flash('That card alredy exists')
            return redirect(url_for('users.add_card', form=form))
        else:
            db.session.add(c_card)
            db.session.commit()
            flash('Card Added')
            return redirect(url_for('users.payment_info'))

    return render_template("add_card.html", form=form)


@users.route('/payment_info/delete/<int:card_id>', methods=['GET', 'POST'])
@login_required
def delete_card(card_id):
    card = Payment_Info.query.filter_by(id=card_id).first()
    if card.user_id != current_user.id:
        abort(403)

    db.session.delete(card)
    db.session.commit()
    flash('Crecit card removed')
    return redirect(url_for('users.payment_info'))

##########################################################################


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():

    if not current_user:
        abort(403)

    form = UpdateUserForm()
    c_email = current_user.email
    c_username = current_user.username
    existing_email = None
    existing_username = None
    f_name = current_user.first_name
    l_name = current_user.last_name
    if form.validate_on_submit():
        print(form.picture.data)
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic
            flash('Picture updated')
            db.session.commit()

        existing_user_name = User.query.filter_by(
            username=form.username.data).first()
        existing_user_email = User.query.filter_by(
            email=form.email.data).first()

        '''current_user.first_name = form.firstname.data
        current_user.last_name = form.lastname.data
        db.session.commit()'''

        if(existing_user_name is not None):
            existing_username = existing_user_name.username

        if(existing_user_email is not None):
            existing_email = existing_user_email.email

        if(len(form.firstname.data) != 0):
            current_user.first_name = form.firstname.data
            db.session.commit()

        if(len(form.lastname.data) != 0):
            current_user.last_name = form.lastname.data
            db.session.commit()

        if existing_email == c_email and existing_username == c_username:
            return redirect(url_for('users.account'))

        if not form.email.data:
            current_user.email = current_user.email
        elif existing_email is None:
            current_user.email = form.email.data
        elif existing_email is not None and existing_email != c_email:

GeekText_Team2/users/templates/change_password.html
<!--{% extends 'base.html' %}
<!--{% block content %}



<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
      integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
      crossorigin="anonymous"
    />
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/stylez.css') }}">


    <style>
      .container span {
        color: #1cb9a4 !important;
      }
    </style>

    <title>Change Password</title>
  </head>

  <body>
    <!-- START HERE -->

    <nav
      class="navbar navbar-expand-md nav-light bg-dark fixed-top py-2"
      id="main-nav"
    >
      <div class="container">
        <a href="{{ url_for('core.home') }}" class="navbar-brand">
          <img src="{{ url_for('static', filename='images/logo.png') }}" width="50" height="50" alt="" />
          <h3 class="d-inline align-middle text-light">Geek<span>Text<span></h3>
        </a>
        <button
          class="navbar-toggler"
          data-toggle="collapse"
          data-target="#navbarCollapse"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a href="{{ url_for('core.home') }}" class="nav-link text-light"
                >Home</a>
            </li>
            <li class="nav-item">
              <a href="{{ url_for('books.list') }}" class="nav-link text-light"
                >Browse</a>
            </li>
            <li class="nav-item">
              <a href="#about" class="nav-link text-light">About</a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle active text-light"
                href="#"
                id="navbarDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                Account
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ url_for('wishlist_posts.addtowhichlist') }}">Wishlist</a>
                <a class="dropdown-item" href="{{ url_for('cart.cart') }}">Shopping Cart</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ url_for('users.account', username=current_user.username) }}"
                  >{{current_user.username}}</a
                >
                <a class="dropdown-item" href="{{ url_for('users.logout') }}"
                  >Logout</a
                >
              </div>
            </li>
            {% else %}
            <li class="nav-item">
              <a
                class="nav-link active text-light"
                href="{{ url_for('users.login') }}"
                tabindex="-1"
                aria-disabled="false"
                >Login</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link active text-light"
                href="{{ url_for('users.register') }}"
                tabindex="-1"
                aria-disabled="false"
                >Register</a
              >
            </li>
            {% endif %}
            <li class="nav-item">
              <a
                class="nav-link active text-light"
                href="{{ url_for('users.register') }}"
                tabindex="-1"
                aria-disabled="false"
                >Cart</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <script
      src="http://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
      integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
      crossorigin="anonymous"
    ></script>

    <script>
      // Get the current year for the copyright
      $("#year").text(new Date().getFullYear());

      $("body").scrollspy({ target: "#main-nav" });

      $("#main-nav a").on("click", function(event) {
        if (this.hash !== "") {
          event.preventDefault();
          const hash = this.hash;

          $("html, body").animate(
            {
              scrollTop: $(hash).offset().top
            },
            800,
            function() {
              window.location.hash = hash;
            }
          );
        }
      });
    </script>
  </body>
  <div class="parallax py-5">
    <div class="container">
      <!-- form card change password -->
      <div id="pw-card" class="card card-outline-secondary">
          <div class="card-header">
              <h3 class="mb-0">Change Password</h3>
          </div>
          <div class="card-body">
              <form class="form" role="form" autocomplete="off" method="POST" action="">
                {{form.hidden_tag()}}
                  <div class="form-group">
                      <label for="inputPasswordOld">Current Password</label>
                      {{form.password(class="form-control")}}
                      {% for error in form.password.errors %}
                      <li style='color:red;'>{{error}}</li>
                      {% endfor %}
                  </div>
                  <div class="form-group">
                      <label for="inputPasswordNew">New Password</label>
                      {{form.new_password(class="form-control")}}
                      {% for error in form.new_password.errors %}
                      <li style='color:red;'>{{error}}</li>
                      {% endfor %}
                      <span class="form-text small text-muted">
                              The password must be 6-15 characters, and must <em>not</em> contain spaces.
                      </span>
                  </div>
                  <div class="form-group">
                      <label for="inputPasswordNewVerify">Verify</label>
                      {{form.new_password_confirm(class="form-control")}}
                      {% for error in form.new_password_confirm.errors %}
                      <li style='color:red;'>{{error}}</li>
                      {% endfor %}
                      <span class="form-text small text-muted">
                              To confirm, type the new password again.
                          </span>
                  </div>
                  <div class="form-group">
                    {{form.submit(class="btn btn-success btn-lg float-right")}}
                  </div>
              </form>
          </div>
      </div>
      <!-- /form card change password -->
    </div>
  </div>
</html>










<style>
  .parallax {
    /* The image used */
    background-image: url("static/images/change_bg.jpg");

    /* Set a specific height */
    width: 100%;
    height: 100%;

    /* Create the parallax scrolling effect */
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
  }

 #pw-card{
   margin-top: 8%;
   border-radius: 0.5rem;
   color: #fff;
   background-color: #343a40;
   box-shadow: 4px 6px 5px #1cb9a4;
   opacity: 0.9;
 }

</style>



<!--{% endblock %}-->

GeekText_Team2/users/templates/edit_address.html
{% extends 'base.html' %} {% block content %}

<script type="text/javascript">
  $("#body-row .collapse").collapse("hide");

  $("#collapse-icon").addClass("fa-angle-double-left");

  $("[data-toggle=sidebar-colapse]").click(function() {
    SidebarCollapse();
  });

  function SidebarCollapse() {
    $(".menu-collapsed").toggleClass("d-none");
    $(".sidebar-submenu").toggleClass("d-none");
    $(".submenu-icon").toggleClass("d-none");
    $("#sidebar-container").toggleClass("sidebar-expanded sidebar-collapsed");

    // Treating d-flex/d-none on separators with title
    var SeparatorTitle = $(".sidebar-separator-title");
    if (SeparatorTitle.hasClass("d-flex")) {
      SeparatorTitle.removeClass("d-flex");
    } else {
      SeparatorTitle.addClass("d-flex");
    }

    $("#collapse-icon").toggleClass(
      "fa-angle-double-left fa-angle-double-right"
    );
  }
</script>

<style>
  #prof_img {
    display: block;
    margin-left: auto;
    margin-right: auto;
  }
  .parallax {
    /* The image used */
    background-image: url("../../../static/images/prof_background.jpg");

    /* Set a specific height */
    min-height: 500px;

    /* Create the parallax scrolling effect */
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
  }
  #prof_col {
    position: absolute;
    width: 850px;
    left: 600px;
    top: 130px;
  }

  #sidebar-container {
    box-shadow: 2px 2px 5px #1cb9a4;
    opacity: 0.9;
    background: #fff;
  }
  .navbar .nav-item {
    font-size: 1.4rem;
    padding-right: 1.4rem;
  }

  #prof-card {
    box-shadow: 4px 6px 5px #1cb9a4;
    opacity: 0.9;
    background: #fff;
  }

  .sticky-offset {
    top: 56px;
  }

  #body-row {
    margin-left: 0;
    margin-right: 0;
  }
  #sidebar-container {
    min-height: 100vh;
    background-color: #333;
    padding: 0;
  }

  /* Sidebar sizes when expanded and expanded */
  .sidebar-expanded {
    width: 230px;
  }
  .sidebar-collapsed {
    width: 60px;
  }

  /* Menu item*/
  #sidebar-container .list-group a {
    height: 50px;
    color: white;
  }

  /* Submenu item*/
  #sidebar-container .list-group .sidebar-submenu a {
    height: 45px;
    padding-left: 30px;
  }
  .sidebar-submenu {
    font-size: 0.9rem;
  }

  /* Separators */
  .sidebar-separator-title {
    background-color: #333;
    height: 35px;
  }
  .sidebar-separator {
    background-color: #333;
    height: 25px;
  }
  .logo-separator {
    background-color: #333;
    height: 60px;
  }

  /* Closed submenu icon */
  #sidebar-container
    .list-group
    .list-group-item[aria-expanded="false"]
    .submenu-icon::after {
    content: " \f0d7";
    font-family: FontAwesome;
    display: inline;
    text-align: right;
    padding-left: 10px;
  }
  /* Opened submenu icon */
  #sidebar-container
    .list-group
    .list-group-item[aria-expanded="true"]
    .submenu-icon::after {
    content: " \f0da";
    font-family: FontAwesome;
    display: inline;
    text-align: right;
    padding-left: 10px;
  }
</style>

<link
  rel="stylesheet"
  type="text/css"
  href="static/css/edit-address-style.css"
/>
<div class="parallax">
  <div class="row" id="body-row">
    <!-- Sidebar -->
    <div
      id="sidebar-container"
      class="sidebar-expanded nav-light bg-dark d-none d-md-block col-2"
    >
      <!-- d-* hiddens the Sidebar in smaller devices. Its itens can be kept on the Navbar 'Menu' -->
      <!-- Bootstrap List Group -->
      <ul class="list-group sticky-top sticky-offset">
        <!-- Separator with title -->
        <li
          class="list-group-item sidebar-separator-title text-muted d-flex align-items-center menu-collapsed"
        >
          <small>USER</small>
        </li>
        <!-- /END Separator -->
        <!-- Menu with submenu -->
        <a href="#" class="bg-dark list-group-item list-group-item-action">
          <div class="d-flex w-100 justify-content-start align-items-center">
            <span class="fa fa-user fa-fw mr-3"></span>
            <span class="menu-collapsed">{{ current_user.username }}</span>
          </div>
        </a>
        <!-- Separator with title -->
        <li
          class="list-group-item sidebar-separator-title text-muted d-flex align-items-center menu-collapsed"
        >
          <small>PROFILE</small>
        </li>

        <a
          href="{{ url_for('users.account') }}"
          class="bg-dark list-group-item list-group-item-action"
        >
          <div class="d-flex w-100 justify-content-start align-items-center">
            <span class="fa fa-user fa-fw mr-3"></span>
            <span class="menu-collapsed">Profile</span>
          </div>
        </a>
        <!-- Submenu content -->
        <a href="{{ url_for('wishlist_posts.addtowhichlist') }}" class="bg-dark list-group-item list-group-item-action">
          <div class="d-flex w-100 justify-content-start align-items-center">
            <span class="fa fa-list fa-fw mr-3"></span>
            <span class="menu-collapsed">Wishlist</span>
          </div>
        </a>
        <!-- /END Separator -->
        <a href="#" class="bg-dark list-group-item list-group-item-action">
          <div class="d-flex w-100 justify-content-start align-items-center">
            <span class="fa fa-shopping-cart fa-fw mr-3"></span>
            <span class="menu-collapsed"
              >Shopping Cart
          </div>
        </a>
        <a
          href="{{ url_for('users.shipping_info') }}"
          class="bg-dark list-group-item list-group-item-action"
        >
          <div class="d-flex w-100 justify-content-start align-items-center">
            <span class="fa fa-truck fa-fw mr-3"></span>
            <span class="menu-collapsed">Shipping Info</span>
          </div>
        </a>
        <a
          href="{{ url_for('users.payment_info') }}"
          class="bg-dark list-group-item list-group-item-action"
        >
          <div class="d-flex w-100 justify-content-start align-items-center">
            <span class="fa fa-credit-card fa-fw mr-3"></span>
            <span class="menu-collapsed">Payment Info</span>
          </div>
        </a>
        <a href="#" class="bg-dark list-group-item list-group-item-action">
          <div class="d-flex w-100 justify-content-start align-items-center">
            <span class="fa fa-thumbs-up fa-fw mr-3"></span>
            <span class="menu-collapsed">Reviews</span>
          </div>
        </a>
        <a href="#" class="bg-dark list-group-item list-group-item-action">
          <div class="d-flex w-100 justify-content-start align-items-center">
            <span class="fa fa-star fa-fw mr-3"></span>
            <span class="menu-collapsed">Favorites</span>
          </div>
        </a>
        <!-- Separator without title -->
        <li class="list-group-item sidebar-separator menu-collapsed"></li>
        <!-- /END Separator -->
        <a href="#" class="bg-dark list-group-item list-group-item-action">
          <div class="d-flex w-100 justify-content-start align-items-center">
            <span class="fa fa-question fa-fw mr-3"></span>
            <span class="menu-collapsed">Help</span>
          </div>
        </a>
        <a
          href="#"
          data-toggle="sidebar-colapse"
          class="bg-dark list-group-item list-group-item-action d-flex align-items-center"
        >
          <div class="d-flex w-100 justify-content-start align-items-center">
            <span id="collapse-icon" class="fa fa-2x mr-3"></span>
            <span id="collapse-text" class="menu-collapsed">Collapse</span>
          </div>
        </a>
        <!-- Logo -->
        <li
          class="list-group-item logo-separator d-flex justify-content-center"
        >
          <img src="static/images/logo.png" width="30" height="30" />
        </li>
      </ul>
      <!-- List Group END-->
    </div>
    <!-- Bootstrap row -->

    <!-- sidebar-container END -->
    <div id="prof_col" class="col-md-9">
      <div id="prof-card" class="card" style="background-color: #343a40;">
        <div class="card-body">
          <div class="row">
            <div class="col-md-12">
              <h4 align="center" class="text-light">
                Edit address
              </h4>
              {% for message in get_flashed_messages() %}
              <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">
                  &times;
                </button>
                {{ message }}
              </div>
              {% endfor %}
            </div>
          </div>
          <hr style="border-top: solid white;" />
          <div class="container" align="center">
            <div class="row">
              <div class="col-lg-12" align="center">
                <form method="POST" action="" enctype="multipart/form-data">
                  {{ form.hidden_tag() }}
                  <div class="form-group row">
                    <label
                      for="username"
                      class="col-3 col-form-label text-light"
                      >Address</label
                    >
                    <div class="col-5">
                      {{ form.address(class="form-control here", type="text" ,placeholder=address.address)}}
                      <!--<input id="username" name="username" placeholder="{{current_user.username}}" class="form-control here" required="required" type="text">-->
                      {% for error in form.address.errors %}
                      <a style="color:red;">{{ error }}</a>
                      {% endfor %}
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-3 col-form-label text-light">City</label>
                    <div class="col-5">
                      {{form.city(class="form-control here", placeholder=address.city)}}
                      {% for error in form.city.errors %}
                      <a style="color:red;">{{ error }}</a>
                      {% endfor %}
                    </div>
                  </div>
                  <div class="form-group row">
                    <label class="col-3 col-form-label text-light">State</label>
                    <div class="col-5">
                      {{ form.state(class='form-control here', type="text", placeholder=address.state) }}
                      {% for error in form.state.errors %}
                      <a style="color:red;">{{ error }}</a>
                      {% endfor %}
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="email" class="col-3 col-form-label text-light"
                      >ZIP</label
                    >
                    <div class="col-5">
                      {{ form.zip_code(class='form-control here',type="text", placeholder=address.postal_code) }}
                      {% for error in form.zip_code.errors %}
                      <a style="color:red;">{{ error }}</a>
                      {% endfor %}
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="newpass" class="col-3 col-form-label text-light"
                      >Phone Number</label
                    >
                    <div class="col-5">
                      {{ form.phone_num(class='form-control here',type="text", placeholder=address.phone_num) }}
                      {% for error in form.phone_num.errors %}
                      <a style="color:red;">{{ error }}</a>
                      {% endfor %}
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="offset-5 col-5">
                      {{ form.submit(class="btn btn-success", type="submit") }}
                      <!--<button name="submit" type="submit" class="btn btn-primary">Update My Profile</button>-->
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}