GeekText_Team2/Wishlist/views.py
from flask import Blueprint, flash, request, render_template, redirect, url_for
from GeekText_Team2 import db
from GeekText_Team2.models import Wishlist, Wishlist2, Wishlist3, Wishlist1, Address, Book, User
from GeekText_Team2.Wishlist.forms import wishlistPostForm
from GeekText_Team2.users.views import current_user

wishlist_posts = Blueprint('wishlist_posts', __name__,
                           template_folder='templates/wishlist')


# @wishlist_posts.route('/create', methods=['GET', 'POST'])
# # @login_required
# def create_wish():

#     form = wishlistPostForm()

# 	if form.validate_on_submit():
# 		 wishlist_post = Wishlist(
# 		 	title=form.title.data,
# 		 	user_id=current_user.id,

# 		 						)
# 		 db.session.add(wishlist_post)
# 		 db.session.commit()
# 		 flash('Wishlist created')
# 		 return redirect(url_for('wishlist_posts.viewallw'))
# 		 # redirect(url_for('Wishlist_posts.list', wishlist_post_id= wishlist_post.id))

#     return render_template('addWish.html', form=form)


@wishlist_posts.route('/delete', methods=['GET'])
def delete():

    item = Wishlist.query.filter_by(
        title="h", user_id=current_user.id, ISBN=request.args.get('ISBN')).first()

    db.session.delete(item)
    db.session.commit()
    flash('Wishlist post Deleted')
    return redirect(url_for('wishlist_posts.viewallw'))


@wishlist_posts.route('/delete1', methods=['GET'])
def delete1():

    item = Wishlist1.query.filter_by(
        title="h", user_id=current_user.id, ISBN=request.args.get('ISBN')).first()

    db.session.delete(item)
    db.session.commit()
    flash('Wishlist post Deleted')
    return redirect(url_for('wishlist_posts.viewallw'))


@wishlist_posts.route('/delete2', methods=['GET'])
def delete2():

    item = Wishlist2.query.filter_by(
        title="h", user_id=current_user.id, ISBN=request.args.get('ISBN')).first()

    db.session.delete(item)
    db.session.commit()
    flash('Wishlist post Deleted')
    return redirect(url_for('wishlist_posts.viewallw'))


@wishlist_posts.route('/delete3', methods=['GET'])
def delete3():

    item = Wishlist3.query.filter_by(
        title="h", user_id=current_user.id, ISBN=request.args.get('ISBN')).first()

    db.session.delete(item)
    db.session.commit()
    flash('Wishlist post Deleted')
    return redirect(url_for('wishlist_posts.viewallw'))


@wishlist_posts.route('/viewall')
def viewallw():
    wishlist_post = Wishlist.query.all()
    items = Book.query.join(Wishlist).filter_by(user_id=current_user.id)
    items1 = Book.query.join(Wishlist1).filter_by(user_id=current_user.id)
    items2 = Book.query.join(Wishlist2).filter_by(user_id=current_user.id)
    items3 = Book.query.join(Wishlist3).filter_by(user_id=current_user.id)
    return render_template('wlist.html', wishlist=wishlist_post, items=items, items1=items1, items2=items2, items3=items3)


@wishlist_posts.route("/addtowishlist", methods=['GET', 'POST'])
def addtowishlist():

    bookId = request.args.get('ISBN')
    item = Wishlist(title="h", user_id=current_user.id, ISBN=bookId)
    db.session.add(item)
    db.session.commit()
    flash('Book added to your wishlist')

    return redirect(url_for('books.list'))


@wishlist_posts.route("/addtowishlist2", methods=['GET', 'POST'])
def addtowishlist2():

    bookId = request.args.get('ISBN')
    item = Wishlist2(title="h", user_id=current_user.id, ISBN=bookId)
    db.session.add(item)
    db.session.commit()
    flash('Book added to your wishlist')

    return redirect(url_for('books.list'))


@wishlist_posts.route("/addtowishlist1", methods=['GET', 'POST'])
def addtowishlist1():

    bookId = request.args.get('ISBN')
    item = Wishlist1(title="h", user_id=current_user.id, ISBN=bookId)
    db.session.add(item)
    db.session.commit()
    flash('Book added to your wishlist')

    return redirect(url_for('books.list'))


@wishlist_posts.route("/addtowishlist3", methods=['GET', 'POST'])
def addtowishlist3():

    bookId = request.args.get('ISBN')
    item = Wishlist3(title="h", user_id=current_user.id, ISBN=bookId)
    db.session.add(item)
    db.session.commit()
    flash('Book added to your wishlist')

    return redirect(url_for('books.list'))


@wishlist_posts.route("/addtowhichlist", methods=['GET', 'POST'])
def addtowhichlist():

    bookId = request.args.get('ISBN')
    item = Wishlist(title="h", user_id=current_user.id, ISBN=bookId)
    db.session.add(item)
    db.session.commit()
    flash('Book added to your wishlist')
    wishlist_post = Wishlist.query.all()
    items = Book.query.join(Wishlist).filter_by(user_id=current_user.id)
    return render_template('whichlist.html', wishlist=wishlist_post, items=items)

GeekText_Team2/blog_posts/views.py
from flask import render_template,url_for,flash, redirect,request,Blueprint
from flask_login import current_user,login_required
from GeekText_Team2 import db             # Import the database
from GeekText_Team2.models import BlogPost
from GeekText_Team2.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts',__name__)           # Creating object instance for a blog post

'''@blog_posts.route('/create',methods=['GET','POST'])
@login_required                                         # User must be logged in
def create_post():
    form = BlogPostForm()                               # Instance of the form

    if form.validate_on_submit():
        rating = request.form.get("rating", None)
        true_private = request.form.get('true_private')
        blog_post = BlogPost(title=form.title.data,# must add here
                             text=form.text.data,
                             user_id=current_user.id,        # Must use the ID of the currently logged in user
                             rating = form.rating.data,
                             true_private = form.true_private.data
                             )
        db.session.add(blog_post)                           # Add changes to the database by creating a blog post
        db.session.commit()                                 # Confirming these changes


        if true_private == 'true_private':
            blog_post = BlogPost(title=form.title.data,# must add here
                                 text=form.text.data,
                                 user_id= 'annonymous',        # Must use the ID of the currently logged in user
                                 rating = form.rating.data,
                                 true_private = form.true_private.data
                                 )
        db.session.add(blog_post)                           # Add changes to the database by creating a blog post
        db.session.commit()


        #db.session.add(blog_post)                           # Add changes to the database by creating a blog post
        #db.session.commit()


        return redirect(url_for('core.index',form=form))

    return render_template('create_post.html',form=form)'''


# int: makes sure that the blog_post_id gets passed as in integer
# instead of a string so we can look it up later.
@blog_posts.route('/<int:blog_post_id>')            # int: forces the post id to be an interger
def blog_post(blog_post_id):
    # grab the requested blog post by id number or return 404
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title,
                            date=blog_post.date,post=blog_post
    )


# Update/edit a blog post
@blog_posts.route("/<int:blog_post_id>/update", methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:            # Make sure the post blog is only able to be edited by the user who created it
        # Forbidden, No Access
        abort(403)

    form = BlogPostForm()                           # Instance of that form, that actually interacts with the python code
    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()

        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))
    # Pass back the old blog post information so they can start again with
    # the old text and title.
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text
    return render_template('create_post.html', title='Update',
                           form=form)

# Delete a blog post
@blog_posts.route("/<int:blog_post_id>/delete", methods=['POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()

    return redirect(url_for('core.index'))

GeekText_Team2/cart/__init__.py
#empty, just need this to import into other .py files

GeekText_Team2/cart/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from GeekText_Team2 import db
from GeekText_Team2.models import Cart, User, Book, Orders, SavedItems
import stripe


cart_blueprint = Blueprint('cart', __name__)

public_key = "pk_test_TYooMQauvdEDq54NiTphI7jx"
stripe.api_key = "sk_test_4eC39HqLyjWDarjtT1zdp7dc"


@cart_blueprint.route('/cart')
@login_required
def cart():
    items = Book.query.join(Cart).add_columns(Cart.userId, Cart.ISBN, Cart.quantity,
                                              Book.price, Book.title, Book.image_url).filter_by(userId=current_user.id)
    totalPrice = 0
    for row in items:
        totalPrice += row.price*row.quantity
    savedItems = Book.query.join(SavedItems).filter_by(userId=current_user.id)
    return render_template('cart.html', totalPrice=totalPrice, items=items, savedItems=savedItems)


@cart_blueprint.route('/addToCart',  methods=['GET', 'POST'])
@login_required
def addToCart():
    bookId = request.args.get('ISBN')
    check = Cart.query.filter_by(userId=current_user.id, ISBN=bookId).first()
    if check is not None:
        return redirect(url_for('cart.cart'))
    item = Cart(userId=current_user.id, ISBN=bookId, quantity=1)
    db.session.add(item)
    db.session.commit()
    flash('Book added to your shopping cart')
    return redirect(url_for('books.list'))


@cart_blueprint.route('/addToSaved',  methods=['GET', 'POST'])
@login_required
def addToSaved():
    bookId = request.args.get('ISBN')
    check = SavedItems.query.filter_by(
        userId=current_user.id, ISBN=bookId).first()
    if check is not None:
        return redirect(url_for('cart.cart'))
    item = SavedItems(userId=current_user.id, ISBN=bookId)
    db.session.add(item)
    db.session.commit()
    flash('Book saved. Look in your cart')
    return redirect(url_for('books.list'))


@cart_blueprint.route('/moveToCart')
@login_required
def moveToCart():
    bookId = request.args.get('ISBN')
    item = Cart(userId=current_user.id, ISBN=bookId, quantity=1)
    savedItem = SavedItems.query.filter_by(
        userId=current_user.id, ISBN=bookId).first()
    db.session.add(item)
    db.session.delete(savedItem)
    db.session.commit()
    flash('Book moved to cart')
    return redirect(url_for('cart.cart'))


@cart_blueprint.route('/moveToSaved')
@login_required
def moveToSaved():
    bookId = request.args.get('ISBN')
    item = SavedItems(userId=current_user.id, ISBN=bookId)
    cartItem = Cart.query.filter_by(
        userId=current_user.id, ISBN=bookId).first()
    db.session.add(item)
    db.session.delete(cartItem)
    db.session.commit()
    flash('Book moved to cart')
    return redirect(url_for('cart.cart'))


@cart_blueprint.route('/removeFromCart')
@login_required
def removeFromCart():
    item = Cart.query.filter_by(
        userId=current_user.id, ISBN=request.args.get('ISBN')).first()
    db.session.delete(item)
    db.session.commit()
    flash('Book removed from your shopping cart')
    return redirect(url_for('cart.cart'))


@cart_blueprint.route('/removeFromSaved')
@login_required
def removeFromSaved():
    item = SavedItems.query.filter_by(
        userId=current_user.id, ISBN=request.args.get('ISBN')).first()
    db.session.delete(item)
    db.session.commit()
    flash('Book removed from your shopping cart')
    return redirect(url_for('cart.cart'))


@cart_blueprint.route('/checkout', methods=['GET', 'POST'])
@login_required
def checkout():
    items = Book.query.join(Cart).filter_by(userId=current_user.id)
    totalPrice = 0
    for row in items:
        item = Cart.query.filter_by(
            userId=current_user.id, ISBN=row.ISBN).first()
        totalPrice += row.price*item.quantity
        order = Orders(userId=current_user.id,
                       ISBN=row.ISBN, quantity=item.quantity)
        db.session.add(order)
        db.session.delete(item)
    db.session.commit()
    return render_template('checkout.html', totalPrice=totalPrice)


@cart_blueprint.route('/addQuantity')
@login_required
def addQuantity():
    bookId = request.args.get('ISBN')
    item = Cart.query.filter_by(userId=current_user.id, ISBN=bookId).first()
    item.quantity += 1
    db.session.commit()
    return redirect(url_for('cart.cart'))


@cart_blueprint.route('/lowerQuantity')
@login_required
def lowerQuantity():
    bookId = request.args.get('ISBN')
    item = Cart.query.filter_by(userId=current_user.id, ISBN=bookId).first()
    item.quantity -= 1
    db.session.commit()
    return redirect(url_for('cart.cart'))


@cart_blueprint.route('/confirmPayment')
@login_required
def confirmPayment():
    items = Book.query.join(Cart).add_columns(Cart.userId, Cart.ISBN, Cart.quantity,
                                              Book.price, Book.title, Book.image_url).filter_by(userId=current_user.id)
    totalPrice = 0
    for row in items:
        item = Cart.query.filter_by(
            userId=current_user.id, ISBN=row.ISBN).first()
        totalPrice += row.price*item.quantity
    return render_template('confirmPayment.html', totalPrice=totalPrice, items=items, public_key=public_key)


@cart_blueprint.route('/payment', methods=['POST'])
@login_required
def charge():
    items = Book.query.join(Cart).filter_by(userId=current_user.id)
    totalPrice = 0
    for row in items:
        item = Cart.query.filter_by(
            userId=current_user.id, ISBN=row.ISBN).first()
        totalPrice += row.price*item.quantity

    amount = int(totalPrice*100)

    customer = stripe.Customer.create(
        email=request.form['stripeEmail'],
        source=request.form['stripeToken'])

    charge = stripe.Charge.create(
        customer=customer.id,
        amount=amount,
        currency='usd')

    return redirect(url_for('cart.checkout'))


# @cart_blueprint.route('/clearOrders')
# @login_required
# def orderErase():
#    orders = Orders.query.filter_by(userId=current_user.id)
#    for row in orders:
#        order = Orders.query.filter_by(userId=current_user.id, ISBN=row.ISBN).first()
#        db.session.delete(order)
#    db.session.commit()
#    return redirect(url_for('cart.cart'))

GeekText_Team2/core/views.py
from flask import render_template, request, Blueprint
from flask_login import login_required
from GeekText_Team2.models import Book
from GeekText_Team2.models import User
from GeekText_Team2.models import BlogPost
from GeekText_Team2.blog_posts.forms import BlogPostForm
from GeekText_Team2 import db
from sqlalchemy import func
from GeekText_Team2.models import User

core = Blueprint('core', __name__)


@core.route('/')
def home():
    bestsellers = Book.query.filter(Book.rating <= 4).limit(4).all()
    b1 = bestsellers[0]
    b2 = bestsellers[1]
    b3 = bestsellers[2]
    b4 = bestsellers[3]
    return render_template('home.html', b1=b1, b2=b2, b3=b3, b4=b4)
# @core.route('/')
# def home():
#     bestsellers = Book.query.filter(Book.soldUnits >= 8).limit(4).all()
#     b1 = bestsellers[0]
#     b2 = bestsellers[1]
#     b3 = bestsellers[2]
#     b4 = bestsellers[3]
#     return render_template('home.html', b1=b1, b2=b2, b3=b3, b4=b4)

# @core.route('/')
# def home():
#    bestsellers = Book.query.filter(Book.soldUnits >= 8).limit(4).all()
#    b1 = bestsellers[0]
#    b2 = bestsellers[1]
#    b3 = bestsellers[2]
#    b4 = bestsellers[3]
#    return render_template('home.html', b1=b1, b2=b2, b3=b3, b4=b4)


@core.route('/welcome')
@login_required
def welcome_user():
    return render_template('welcome_user.html')


@core.route('/info')
def info():
    '''
    Example view of any other "core" page. Such as a info page, about page,
    contact page. Any page that doesn't really sync with one of the models.
    '''
    return render_template('info.html')


@core.route('/index')                            # Main page
def index():
    '''
    This is the home page view. Notice how it uses pagination to show a limited
    number of posts by limiting its query size and then calling paginate.
    '''

    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(
        BlogPost.date.desc()).paginate(page=page, per_page=10)
    # Returns an instance of the main page
    # Links to the index template
    return render_template('index.html', blog_posts=blog_posts)

GeekText_Team2/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% block head %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
      integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
      crossorigin="anonymous"
    />
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/stylez.css') }}">
    <link rel="icon" href="static/images/white_logo.ico">


    <style>
      .container span {
        color: #1cb9a4 !important;
      }
    </style>

    <title>GeekText</title>
  </head>
  {% endblock %}
  
  <body>
    <!-- START HERE -->

    <nav
      class="navbar navbar-expand-md nav-light bg-dark fixed-top py-2"
      id="main-nav"
    >
      <div class="container">
        <a href="{{ url_for('core.home') }}" class="navbar-brand">
          <img src="{{ url_for('static', filename='images/logo.png') }}" width="50" height="50" alt="" />
          <h3 class="d-inline align-middle text-light">Geek<span>Text<span></h3>
        </a>
        <button
          class="navbar-toggler"
          data-toggle="collapse"
          data-target="#navbarCollapse"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a href="{{ url_for('core.home') }}" class="nav-link text-light"
                >Home</a>
            </li>
            <li class="nav-item">
              <a href="{{ url_for('books.list') }}" class="nav-link text-light"
                >Browse</a>
            </li>
            <li class="nav-item">
              <a href="#about" class="nav-link text-light">About</a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle active text-light"
                href="#"
                id="navbarDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                Account
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ url_for('wishlist_posts.addtowhichlist') }}">Wishlist</a>
                <a class="dropdown-item" href="{{ url_for('cart.cart') }}">Shopping Cart</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ url_for('users.account', username=current_user.username) }}"
                  >{{current_user.username}}</a
                >
                <a class="dropdown-item" href="{{ url_for('users.logout') }}"
                  >Logout</a
                >
              </div>
            </li>
            {% else %}
            <li class="nav-item">
              <a
                class="nav-link active text-light"
                href="{{ url_for('users.login') }}"
                tabindex="-1"
                aria-disabled="false"
                >Login</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link active text-light"
                href="{{ url_for('users.register') }}"
                tabindex="-1"
                aria-disabled="false"
                >Register</a
              >
            </li>
            {% endif %}
            <li class="nav-item">
              <a
                class="nav-link active text-light"
                href="{{ url_for('cart.cart') }}"
                tabindex="-1"
                aria-disabled="false"
                >Cart</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block sidenav %}
    {% endblock %}

    {% block content%} {% endblock %}

    <script
      src="http://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
      integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
      crossorigin="anonymous"
    ></script>

    <script>
      // Get the current year for the copyright
      $("#year").text(new Date().getFullYear());

      $("body").scrollspy({ target: "#main-nav" });

      $("#main-nav a").on("click", function(event) {
        if (this.hash !== "") {
          event.preventDefault();
          const hash = this.hash;

          $("html, body").animate(
            {
              scrollTop: $(hash).offset().top
            },
            800,
            function() {
              window.location.hash = hash;
            }
          );
        }
      });
    </script>
  </body>
  {% block footer %}
  {% endblock  %}
</html>

GeekText_Team2/templates/blog_post.html
{% extends "base.html" %}       <!-- .html page for showing you a single blog post -->
{% block content %}
<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
  <p>{{post.text}}</p>
  <!-- Python Script -->
   {% if post.author == current_user %}     <!-- Notice the syntax using current_user % -->
     <div>
       <a class="btn btn-secondary" href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>  <!-- Confirm changes -->
     </div>
   {% endif %}
</div>




  <!-- Modal for Pop Up, taken from booststrap-->
  {# https://getbootstrap.com/docs/4.1/components/modal/ #}
  {# Notice how the link with the id to the button above! #}
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">   <!-- Delete post from database -->
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

GeekText_Team2/templates/cart.html
{% extends 'base.html' %} {% block content %}
<head>
    <link rel="stylesheet" href="static/css/style.css" />
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>


<div class="container">
        {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">
            &times;
          </button>
          {{ message }}
        </div>
        {% endfor %}
    <table id="cart" class="table table-hover table-condensed">
        <thead>
            <tr>
                <th style="width:50%">Product</th>
                <th style="width:8%">Price</th>
                <th style="width:10%">Quantity</th>
                <th style="width:22%" class="text-center">Subtotal</th>
                <th style="width:10%"></th>
            </tr>
        </thead>
        {% for row in items %}
        <tbody>
            <tr>
                <td data-th="Product">
                    <div class="row">
                        <div class="col-sm-2 hidden-xs"><img src="{{row.image_url}}" alt="..." class="img-responsive" style="width: 72px; height: 100px;" /></div>
                        <div class="col-sm-10">
                            <h4 class="nomargin">{{row.title}}</h4>
                        </div>
                    </div>
                </td>
                <td data-th="Price">${{row.price}}</td>
                <td data-th="Quantity">
                    {{row.quantity}}
                    <a href="/addQuantity?ISBN={{row.ISBN}}" class="btn btn-info btn-sm">+</a>
                    <a href="/lowerQuantity?ISBN={{row.ISBN}}" class="btn btn-info btn-sm">-</a>
                </td>
                <td data-th="Subtotal" class="text-center">{{row.price*row.quantity}}</td>
                <td class="actions" data-th="">
                    <a href="/removeFromCart?ISBN={{row.ISBN}}" class="btn btn-primary">Remove</a>
                </td>
                <td class="actions" data-th="Move to Cart">
                    <a href="/moveToSaved?ISBN={{row.ISBN}}" class="btn btn-primary">Move to Saved</a>
                </td>
            </tr>
        </tbody>
        {% endfor %}
        <tfoot>
            <tr>
                <td><a href="{{url_for('books.list')}}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
                <td colspan="2" class="hidden-xs"></td>
                <td class="hidden-xs text-center"><strong>Total ${{totalPrice}}</strong></td>
                <td><a href="{{ url_for('cart.confirmPayment')}}"  class="btn btn-success btn-block">Checkout <i class="fa fa-angle-right"></i></a></td>
            </tr>
        </tfoot>
    </table>
</div>
<div class="container">
    <table id="cart" class="table table-hover table-condensed">
        <thead>
            <tr>
                <th style="width:50%">Saved For Later</th>
                <th style="width:40%"></th>
                <th style="width:10%"></th>
            </tr>
        </thead>
        {% for row in savedItems %}
        <tbody>
            <tr>
                <td data-th="Saved For Later">
                    <div class="row">
                        <div class="col-sm-2 hidden-xs"><img src="{{row.image_url}}" alt="..." class="img-responsive" style="width: 72px; height: 100px;" /></div>
                        <div class="col-sm-10">
                            <h4 class="nomargin">{{row.title}}</h4>
                        </div>
                    </div>
                </td>
                <td></td>
                <td class="actions" data-th="Move to Cart">
                    <a href="/moveToCart?ISBN={{row.ISBN}}" class="btn btn-primary">Move to Cart</a>
                </td>
                <td class="actions" data-th="">
                    <a href="/removeFromSaved?ISBN={{row.ISBN}}" class="btn btn-primary">Remove</a>
                </td>
            </tr>
        </tbody>
        {% endfor %}
</div>  {% endblock %}

GeekText_Team2/templates/email_confirmation.html
{# GeekText_Team2/templates/email_confirmation.html #}

Your account on Kennedy Family Recipes was successfully created.<br>
Please click the link below to confirm your email address and<br>
activate your account:

<p>
<a href="{{ confirm_url }}">{{ confirm_url }}</a>
</p>

<p>
--<br>
Questions? Comments? Email kennedyfamilyrecipes@gmail.com.
</p>