GeekText_Team2/books/forms.py
from flask_wtf import FlaskForm                         # Imports the forms API
from wtforms import StringField, SubmitField, TextAreaField     # Specific forms that are needed
from wtforms.validators import DataRequired                     # validators for these forms


class BlogPostForm(FlaskForm):
    # no empty titles or text possible
    # we'll grab the date automatically from the Model later
    title = StringField('Title', validators=[DataRequired()])                   # Title of post
    text = TextAreaField('Text', validators=[DataRequired()])                   # Tesxt of post
    rating = StringField('rating', validators=[DataRequired()])
    true_private = StringField('true_private')
    book_isbn = StringField()
    submit = SubmitField('Submit')                                            # Button to submit

GeekText_Team2/books/views.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import current_user, login_required
from GeekText_Team2 import db
from sqlalchemy import func
from GeekText_Team2.models import Book
from GeekText_Team2.models import BlogPost
from GeekText_Team2.blog_posts.forms import BlogPostForm
from GeekText_Team2.models import User
from GeekText_Team2.models import Cart
from GeekText_Team2.models import Orders
from sqlalchemy import desc

books_blueprint = Blueprint(
    'books', __name__, template_folder='templates/books')


@books_blueprint.route('/books/all')
def list():
    stop_pagination = False
    page = request.args.get('page', 1, type=int)
    sort_by = request.args.get('sort_by')
    descending = request.args.get('desc')

    if descending:
        books = Book.query.order_by(
            desc(sort_by)).paginate(page=page, per_page=12)
    else:
        books = Book.query.order_by(sort_by).paginate(page=page, per_page=12)

    raw_genres = Book.query.with_entities(
        Book.genre).group_by(Book.genre).all()
    genres = []

    for word in raw_genres:
        word = str(word)
        word = (word).replace('(', '').replace(')',
                                               '').replace('\'', '').replace(',', '')
        genres.append(word)

    return render_template('new_browse.html', books=books, genres=genres, stop_pagination=stop_pagination)

    return render_template('new_browse.html', books=books, genres=genres, stop_pagination=stop_pagination)


@books_blueprint.route('/books/genre')
def genre():
    page = request.args.get('page', 1, type=int)
    genre = request.args.get('genre')
    sort_by = request.args.get('sort_by')
    descending = request.args.get('desc')

    if descending:
        books = Book.query.filter_by(genre=genre).order_by(
            desc(sort_by)).paginate(page=page, per_page=12)
    else:
        books = Book.query.filter_by(genre=genre).order_by(
            sort_by).paginate(page=page, per_page=12)

    raw_genres = Book.query.with_entities(
        Book.genre).group_by(Book.genre).all()
    genres = []

    for word in raw_genres:
        word = str(word)
        word = (word).replace('(', '').replace(')',
                                               '').replace('\'', '').replace(',', '')
        genres.append(word)

    return render_template('new_genre.html', genre=genre, books=books, genres=genres)


@books_blueprint.route('/books/best_sellers')
def best_sellers():
    stop_pagination = True
    books = Book.query.order_by(desc('soldUnits')).paginate(per_page=6)
    raw_genres = Book.query.with_entities(
        Book.genre).group_by(Book.genre).all()
    genres = []

    for word in raw_genres:
        word = str(word)
        word = (word).replace('(', '').replace(')',
                                               '').replace('\'', '').replace(',', '')
        genres.append(word)

    return render_template('best_sellers.html', books=books, genres=genres)


@books_blueprint.route('/books/best_rated')
def best_rated():
    stop_pagination = True
    books = Book.query.order_by(desc('rating')).paginate(per_page=6)
    raw_genres = Book.query.with_entities(
        Book.genre).group_by(Book.genre).all()
    genres = []

    for word in raw_genres:
        word = str(word)
        word = (word).replace('(', '').replace(')',
                                               '').replace('\'', '').replace(',', '')
        genres.append(word)

    return render_template('best_rated.html', books=books, genres=genres)


@books_blueprint.route('/books/new_releases')
def new_releases():
    stop_pagination = True
    books = Book.query.order_by(desc('releaseDate')).paginate(per_page=6)
    raw_genres = Book.query.with_entities(
        Book.genre).group_by(Book.genre).all()
    genres = []

    for word in raw_genres:
        word = str(word)
        word = (word).replace('(', '').replace(')',
                                               '').replace('\'', '').replace(',', '')
        genres.append(word)

    return render_template('new_releases.html', books=books, genres=genres)


@books_blueprint.route('/browse/authors')
def author():
    author = request.args.get('author')
    books = Book.query.filter_by(author=author).paginate(per_page=10)
    print(type(books))
    return render_template('new_browse.html', author=author, books=books)


# @books_blueprint.route('/browse/authors/<author>')
# def author(author):
#     #grab list of books based on author from db
#     books = Book.query.filter_by(author=author)
#     return render_template('list.html', author=author, books=books)

@books_blueprint.route('/browse/<ISBN>', methods=['GET', 'POST'])
def browse(ISBN):  # was named details
    # grab book details
    books = Book.query.filter_by(ISBN=ISBN).first()
    user = User.query.filter_by(id=User.id).first_or_404()

    if current_user.is_authenticated:
        orders = Orders.query.filter_by(userId=current_user.id)
        order = Orders.query.filter_by(
            userId=current_user.id, ISBN=ISBN).first()

    else:
        order = None
        orders = None

    form = BlogPostForm()
    page = request.args.get('page', 1, type=int)
    #blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=10)
    blog_posts = BlogPost.query.filter_by(
        book_isbn=ISBN).order_by(BlogPost.date.desc())
    # Returns an instance of the main page

    if form.validate_on_submit():
        rating = request.form.get("rating", None)
        true_private = request.form.get('true_private')
        blog_post = BlogPost(title=form.title.data,  # must add here
                             text=form.text.data,
                             user_id=current_user.id,        # Must use the ID of the currently logged in user
                             rating=form.rating.data,
                             true_private=form.true_private.data,
                             book_isbn=ISBN
                             )
        # db.session.add(blog_post)                           # Add changes to the database by creating a blog post
        # db.session.commit()                                 # Confirming these changes
        flash("Blog Post Created")

        if true_private == 'true_private':
            blog_post = BlogPost(title=form.title.data,  # must add here
                                 text=form.text.data,
                                 user_id=current_user.id,        # Must use the ID of the currently logged in user
                                 rating=form.rating.data,
                                 true_private=form.true_private.data,
                                 book_isbn=ISBN
                                 )
        # Add changes to the database by creating a blog post
        db.session.add(blog_post)
        db.session.commit()

        store_isbn = Book.query.filter_by(ISBN=ISBN)
        #page = request.args.get('page', 1, type=int)
        #blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=10)
        # Returns an instance of the main page

    return render_template('bookentry.html', ISBN=ISBN, books=books, blog_posts=blog_posts, book_isbn=ISBN, form=form, store_isbn=ISBN, order=order, orders=orders, user=user)

GeekText_Team2/books/templates/books/author.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Browse Books</h1>
  {% for book in books  %}
  <div class="card mb-3">
    <div class="row no-gutters">
      <div class="col-md-1">
        <a href="#">
          <img  src="{{book.image_url}}" class="card-img-overlay" width=auto height=auto alt="...">
        </a>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <a style="font-size:32px" href="/browse/{{book.ISBN}}">{{book.title}}</a>
          <p style="font-size:14px">by {{book.author}}</p>
          <p class="text-left">{{ book.description }}</p>
          <p class="card-text"><small class="text-muted">Published in {{ book.publication_year }}</small></p>
          <a href="#" class="btn btn-primary">Add to Cart</a>
          <a href="#" class="btn btn-secondary">Add to Wishlist</a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}

</div>
{% endblock %}

GeekText_Team2/books/templates/books/best_rated.html
{% extends "base.html" %} {% block content %}

<div
  id="b-back"
  class="container-fluid py-5"
  style="background: lightgray; background-image: url({{ url_for('static', filename='images/browse_background.jpg') }}); height: 50%; background-position: center; background-repeat: no-repeat;background-size: cover;"
>
  <!-- Page Content -->
  <div class="container py-5" style="background: white">
    <div class="row">
      <div class="col-lg-3">
        <h2 class="my-4" style="text-align: center">Genres</h2>

        <!--GENRE MENU-->
        <div class="list-group" style="font-size: 20px">
          <a href="{{ url_for('books.list') }}" class="list-group-item">All</a>
          {% for genre in genres %}
          <a
            href="{{ url_for('books.genre', genre=genre) }}"
            class="list-group-item"
            >{{ genre }}</a
          >
          {% endfor %}
        </div>

        <!--SORT DROPDOWN-->
        <!-- <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Sort By
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{{ url_for('books.list', sort_by='price') }}">Price Low-High</a>
            <a class="dropdown-item" href="{{ url_for('books.list', sort_by='author') }}">Author Name A-Z</a>
            <a class="dropdown-item" href="{{ url_for('books.list', sort_by='title') }}">Book Title A-Z</a>
            <a class="dropdown-item" href="{{ url_for('books.list', sort_by='rating') }}">Ratings Low-High</a>
            </div>
          </div> -->
      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">
        <div
          class="jumbotron"
          style="background-image: url(../../../static/images/Most-Loved3.jpg); height: 350px;"
        ></div>

        <!--BOOK ITEMS-->

        <div class="row">
          {% for book in books.items %}

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"
                ><img class="card-img-top" src="{{ book.image_url }}" alt=""
              /></a>
              <div class="card-body">
                <h5 class="card-title" style="text-align: center">
                  <a href="#">{{ book.title }}</a>
                </h5>

                <div class="text-muted" style="text-align: center">
                  <a href="#" style="color: darkblue">By {{ book.author }}</a>
                </div>

                <p style="text-align: center">${{ book.price }}</p>
                <div class="row">
                  <div class="btn-group-vertical" style="margin: auto">
                    <a href="/addToCart?ISBN={{book.ISBN}}" class="btn btn-primary">Add to Cart</a>
                    <a href="#" class="btn btn-secondary">Add to Wishlist</a>
                    <a href="/addToSaved?ISBN={{book.ISBN}}" class="btn btn-secondary">Save For Later</a>
                  </div>
                </div>
              </div>
              <div class="card-footer">
                <small class="text-muted">{{ book.rating }}&#9733;</small>
              </div>
            </div>
          </div>

          {% endfor %} {% if stop_pagination == False %} {% for page_num in
          books.iter_pages(left_edge=1, right_edge=1, left_current=1,
          right_current=2) %} {% if page_num %} {% if books.page == page_num %}
          <a
            class="btn btn-info mb-4"
            href="{{ url_for('books.list', page=page_num) }}"
            >{{ page_num }}</a
          >
          {% else %}
          <a
            class="btn btn-outline-info mb-4"
            href="{{ url_for('books.list', page=page_num) }}"
            >{{ page_num }}</a
          >
          {% endif %} {% else %} ... {% endif %} {% endfor %} {% endif %}
        </div>
        <!-- /.row -->
      </div>
      <!-- /.col-lg-9 -->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark-fluid">
    <div class="container">
      <p class="m-0 text-center text-white">Geek<span>Text</span> 2019</p>
    </div>
    <!-- /.container -->
  </footer>
</div>

{% endblock %}

GeekText_Team2/books/templates/books/best_sellers.html
{% extends "base.html" %} {% block content %}

<div
  class="container-fluid"
  style="background: lightgray; background-image: url({{ url_for('static', filename='images/browse_background.jpg') }}); height: 50%; background-position: center; background-repeat: no-repeat;background-size: cover;"
>
  <!-- Page Content -->
  <div class="container" style="background: white">
    <div class="row">
      <div class="col-lg-3">
        <h2 class="my-4" style="text-align: center">Genres</h2>

        <!--GENRE MENU-->
        <div class="list-group" style="font-size: 20px">
          <a href="{{ url_for('books.list') }}" class="list-group-item">All</a>
          {% for genre in genres %}
          <a
            href="{{ url_for('books.genre', genre=genre) }}"
            class="list-group-item"
            >{{ genre }}</a
          >
          {% endfor %}
        </div>

        <!--SORT DROPDOWN-->
        <!-- <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Sort By
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{{ url_for('books.list', sort_by='price') }}">Price Low-High</a>
            <a class="dropdown-item" href="{{ url_for('books.list', sort_by='author') }}">Author Name A-Z</a>
            <a class="dropdown-item" href="{{ url_for('books.list', sort_by='title') }}">Book Title A-Z</a>
            <a class="dropdown-item" href="{{ url_for('books.list', sort_by='rating') }}">Ratings Low-High</a>
            </div>
          </div> -->
      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">
        <div
          class="jumbotron"
          style="background-image: url(../../../static/images/Top-Sellers.jpg); height: 350px;"
        ></div>

        <!--BOOK ITEMS-->

        <div class="row">
          {% for book in books.items %}

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"
                ><img class="card-img-top" src="{{ book.image_url }}" alt=""
              /></a>
              <div class="card-body">
                <h5 class="card-title" style="text-align: center">
                  <a href="#">{{ book.title }}</a>
                </h5>

                <div class="text-muted" style="text-align: center">
                  <a href="#" style="color: darkblue">By {{ book.author }}</a>
                </div>

                <p style="text-align: center">${{ book.price }}</p>
                <div class="row">
                  <div class="btn-group-vertical" style="margin: auto">
                    <a href="/addToCart?ISBN={{book.ISBN}}" class="btn btn-primary">Add to Cart</a>
                    <a href="#" class="btn btn-secondary">Add to Wishlist</a>
                    <a href="/addToSaved?ISBN={{book.ISBN}}" class="btn btn-secondary">Save For Later</a>
                  </div>
                </div>
              </div>
              <div class="card-footer">
                <small class="text-muted">{{ book.rating }}&#9733;</small>
              </div>
            </div>
          </div>

          {% endfor %} {% if stop_pagination == False %} {% for page_num in
          books.iter_pages(left_edge=1, right_edge=1, left_current=1,
          right_current=2) %} {% if page_num %} {% if books.page == page_num %}
          <a
            class="btn btn-info mb-4"
            href="{{ url_for('books.list', page=page_num) }}"
            >{{ page_num }}</a
          >
          {% else %}
          <a
            class="btn btn-outline-info mb-4"
            href="{{ url_for('books.list', page=page_num) }}"
            >{{ page_num }}</a
          >
          {% endif %} {% else %} ... {% endif %} {% endfor %} {% endif %}
        </div>
        <!-- /.row -->
      </div>
      <!-- /.col-lg-9 -->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark-fluid">
    <div class="container">
      <p class="m-0 text-center text-white">GeekText 2019</p>
    </div>
    <!-- /.container -->
  </footer>
</div>

{% endblock %}

GeekText_Team2/books/templates/books/new_browse.html
{% extends "base.html" %} {% block content %}

<div
  class="container-fluid py-5"
  style="background: lightgray; background-image: url({{ url_for('static', filename='images/browse_background.jpg') }}); height: 50%; background-position: center; background-repeat: no-repeat;background-size: cover;"
>
  <!-- Page Content -->
  <div class="container" style="background: white">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">
        &times;
      </button>
      {{ message }}
    </div>
    {% endfor %}
    <div class="row">
      <div class="col-lg-3">
        <h2 class="my-4" style="text-align: center">Genres</h2>

        <!--GENRE MENU-->
        <div class="list-group" style="font-size: 20px">
          <a href="{{ url_for('books.list') }}" class="list-group-item">All</a>
          {% for genre in genres %}
          <a
            href="{{ url_for('books.genre', genre=genre) }}"
            class="list-group-item"
            >{{ genre }}</a
          >
          {% endfor %}
        </div>
        <p>This is the new_browse.html page</p>
        <!--SORT DROPDOWN-->
        <div class="dropdown">
          <button
            class="btn btn-secondary dropdown-toggle"
            type="button"
            id="dropdownMenuButton"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            Sort By
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a
              class="dropdown-item"
              href="{{ url_for('books.list', sort_by='price') }}"
              >Price Low-High</a
            >
            <a
              class="dropdown-item"
              href="{{ url_for('books.list', sort_by='price', desc=True) }}"
              >Price High-Low</a
            >
            <a
              class="dropdown-item"
              href="{{ url_for('books.list', sort_by='author') }}"
              >Author Name A-Z</a
            >
            <a
              class="dropdown-item"
              href="{{ url_for('books.list', sort_by='title') }}"
              >Book Title A-Z</a
            >
            <a
              class="dropdown-item"
              href="{{ url_for('books.list', sort_by='rating') }}"
              >Ratings Low-High</a
            >
            <a
              class="dropdown-item"
              href="{{ url_for('books.list', sort_by='rating', desc=True) }}"
              >Ratings High-Low</a
            >
          </div>
        </div>
      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">
        <div
          id="carouselExampleIndicators"
          class="carousel slide my-4"
          data-ride="carousel"
        >
          <ol class="carousel-indicators">
            <li
              data-target="#carouselExampleIndicators"
              data-slide-to="0"
              class="active"
            ></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <a href="{{ url_for('books.best_sellers') }}">
                <img
                  class="d-block img-fluid"
                  src="../../../static/images/Top-Sellers.jpg"
                  alt="First slide"
                />
              </a>
            </div>
            <div class="carousel-item">
              <a href="{{ url_for('books.best_rated') }}">
                <img
                  class="d-block img-fluid"
                  src="../../../static/images/Most-Loved3.jpg"
                  alt="Second slide"
                />
              </a>
            </div>
            <div class="carousel-item">
              <a href="{{ url_for('books.new_releases') }}">
                <img
                  class="d-block img-fluid"
                  src="../../../static/images/new-releases.jpg"
                  alt="Third slide"
                />
              </a>
            </div>
          </div>
          <a
            class="carousel-control-prev"
            href="#carouselExampleIndicators"
            role="button"
            data-slide="prev"
          >
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a
            class="carousel-control-next"
            href="#carouselExampleIndicators"
            role="button"
            data-slide="next"
          >
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <!--BOOK ITEMS-->

        <div class="row">
          {% for book in books.items %}

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"
                ><img class="card-img-top" src="{{ book.image_url }}" alt=""
              /></a>
              <div class="card-body">
                <h5 class="card-title" style="text-align: center">
                  <a href="/browse/{{ book.ISBN }}">{{ book.title }}</a>
                </h5>

                <div class="text-muted" style="text-align: center">
                  <a href="#" style="color: darkblue">By {{ book.author }}</a>
                </div>

                <p style="text-align: center">${{ book.price }}</p>
                <div class="row">
                  <div class="btn-group-vertical" style="margin: auto">
                    <a
                      href="/addToCart?ISBN={{ book.ISBN }}"
                      class="btn btn-primary"
                      >Add to Cart</a
                    >
                    <a
                      href="/addtowhichlist?ISBN={{ book.ISBN }}"
                      class="btn btn-secondary"
                      >Add to Wishlist</a
                    >
                    <a
                      href="/addToSaved?ISBN={{ book.ISBN }}"
                      class="btn btn-secondary"
                      >Save For Later</a
                    >
                  </div>
                </div>
              </div>
              <div class="card-footer">
                <small class="text-muted">{{ book.rating }}&#9733;</small>
              </div>
            </div>
          </div>

          {% endfor %} {% if stop_pagination == False %} {% for page_num in
          books.iter_pages(left_edge=1, right_edge=1, left_current=1,
          right_current=2) %} {% if page_num %} {% if books.page == page_num %}
          <a
            class="btn btn-info mb-4"
            href="{{ url_for('books.list', page=page_num) }}"
            >{{ page_num }}</a
          >
          {% else %}
          <a
            class="btn btn-outline-info mb-4"
            href="{{ url_for('books.list', page=page_num) }}"
            >{{ page_num }}</a
          >
          {% endif %} {% else %} ... {% endif %} {% endfor %} {% endif %}
        </div>
        <!-- /.row -->
      </div>
      <!-- /.col-lg-9 -->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark-fluid">
    <div class="container">
      <p class="m-0 text-center text-white">GeekText 2019</p>
    </div>
    <!-- /.container -->
  </footer>
</div>

{% endblock %}

GeekText_Team2/books/templates/books/new_genre.html
{% extends "base.html" %} {% block content %}

<link
  href="https://fonts.googleapis.com/css?family=Pacifico&display=swap"
  rel="stylesheet"
/>

<div
  class="container-fluid py-5"
  style="background: lightgray; background-image: url({{ url_for('static', filename='images/browse_background.jpg') }}); height: 100%; background-position: center; background-repeat: no-repeat;background-size: cover;"
>
  <!-- Page Content -->
  <div class="container py-5" style="background: white">
    <div class="row">
      <div class="col-lg-3">
        <h2 class="my-4" style="text-align: center">Genres</h2>

        <!--GENRE MENU-->
        <div class="list-group" style="font-size: 20px">
          <a href="{{ url_for('books.list') }}" class="list-group-item">All</a>
          {% for genre in genres %}
          <a
            href="{{ url_for('books.genre', genre=genre) }}"
            class="list-group-item"
            >{{ genre }}</a
          >
          {% endfor %}
        </div>

        <!--SORT DROPDOWN-->
        <div class="dropdown">
          <button
            class="btn btn-secondary dropdown-toggle"
            type="button"
            id="dropdownMenuButton"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            Sort By
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a
              class="dropdown-item"
              href="{{ url_for('books.genre', genre=genre,sort_by='price') }}"
              >Price Low-High</a
            >
            <a
              class="dropdown-item"
              href="{{ url_for('books.genre', genre=genre,sort_by='price', desc=True) }}"
              >Price High-Low</a
            >
            <a
              class="dropdown-item"
              href="{{ url_for('books.genre', genre=genre,sort_by='author') }}"
              >Author Name A-Z</a
            >
            <a
              class="dropdown-item"
              href="{{ url_for('books.genre', genre=genre,sort_by='title') }}"
              >Book Title A-Z</a
            >
            <a
              class="dropdown-item"
              href="{{ url_for('books.genre', genre=genre,sort_by='rating') }}"
              >Ratings Low-High</a
            >
            <a
              class="dropdown-item"
              href="{{ url_for('books.genre', genre=genre,sort_by='rating', desc=True) }}"
              >Ratings High-Low</a
            >
          </div>
        </div>
      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">
        <div
          class="jumbotron"
          style="background-image: url(../../../static/images/color-background.png)"
        >
          <h1
            class="my-0"
            style="text-align: center; font-family: 'Vollkorn', serif; color: white"
          >
            BROWSE {{ genre | upper }} TITLES
          </h1>
        </div>

        <!--BOOK ITEMS-->

        <div class="row">
          {% for book in books.items %}

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="#"
                ><img class="card-img-top" src="{{ book.image_url }}" alt=""
              /></a>
              <div class="card-body">
                <h5 class="card-title" style="text-align: center">
                  <a href="/browse/{{book.ISBN}}">{{ book.title }}</a>
                </h5>

                <div class="text-muted" style="text-align: center">
                  <a href="/browse/authors" style="color: darkblue">By {{ book.author }}</a>
                </div>

                <h5>
                  <p style="text-align: center">${{ book.price }}</p>
                </h5>

                <div class="row">
                  <div class="btn-group-vertical" style="margin: auto">
                    <a href="/addToCart?ISBN={{book.ISBN}}" class="btn btn-primary">Add to Cart</a>
                    <a href="#" class="btn btn-secondary">Add to Wishlist</a>
                    <a href="/addToSaved?ISBN={{book.ISBN}}" class="btn btn-secondary">Save For Later</a>
                  </div>
                </div>
              </div>

              <div class="card-footer">
                <small class="text-muted">{{ book.rating }}&#9733;</small>
              </div>
            </div>
          </div>

          {% endfor %} {% for page_num in books.iter_pages(left_edge=1,
          right_edge=1, left_current=1, right_current=2) %} {% if page_num %} {%
          if books.page == page_num %}
          <a
            class="btn btn-info mb-4"
            href="{{ url_for('books.genre', genre=genre, page=page_num) }}"
            >{{ page_num }}</a
          >
          {% else %}
          <a
            class="btn btn-outline-info mb-4"
            href="{{ url_for('books.genre', genre=genre, page=page_num) }}"
            >{{ page_num }}</a
          >
          {% endif %} {% else %} ... {% endif %} {% endfor %}
        </div>
        <!-- /.row -->
      </div>
      <!-- /.col-lg-9 -->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark-fluid">
    <div class="container">
      <p class="m-0 text-center text-white">GeekText 2019</p>
    </div>
    <!-- /.container -->
  </footer>
</div>

{% endblock %}